PLT-33: ClusterHealth alert support
spectrocloud/terraform-provider-spectrocloud pull request #139
Opened 2022-11-13 18:00 UTC by SivaanandM

## Jira 
https://spectrocloud.atlassian.net/browse/PLT-33

## Change Description
Terrafrom - Enabled project level cluster health alerts ( email | http ).

## Type of change
- [*] New feature (non-breaking change which adds functionality)

## Documentation
https://docs.spectrocloud.com/clusters/cluster-management/health-alerts#overview

**Validation ** 

- Tried to create alert resources with below combinations 
      - With one email & one web-hook alert configuration.
      - with only email alert configuration.
      - With 2 web-hook alert configuration.
      - With only web-hook alert configuration.
-  Validated with all CRUD operations with resources.

**Support** 

1. Added documentation for `spectrocloud_alert`
2. Included examples for alert creation, few combinations

2022-11-14 16:54 UTC, nikchern requested changes

2022-11-14 16:54 UTC, nikchern commented on examples/resources/spectrocloud_alert/providers.tf
> +      version = ">= 0.1"
Please put specific version here from which we support it. I.e. 0.10.4

2022-11-15 03:27 UTC, resmaa requested changes

2022-11-15 03:27 UTC, resmaa commented on examples/resources/spectrocloud_alert/resource.tf
> +
```suggestion
**Note** - We can set up a maximum of two alerts for cluster health per project. Webhook can be configured in the HTTP component, and for email, we can add a target email recipient or enable alerts for all users in the corresponding project
```

2022-11-15 03:27 UTC, resmaa commented on docs/resources/alert.md
> +
```suggestion
- Spectro Cloud  creates up to two alerts from the below combinations:
		 - 1 email alert (can add any number of email recipients) & 1 HTTP webhook alert.
		 - 2 HTTP Webhook alert configurations.
		 - Anyone alert type Email/HTTP.
```

2022-11-15 04:53 UTC, resmaa approved these changes

2022-11-15 17:49 UTC, nikchern approved these changes

2022-11-17 18:44 UTC, nikchern requested changes
As discussed we need to use a different endpoint with alert uid

2022-11-21 20:11 UTC, SivaanandM commented
> 

@nikchern updated the alert support with alertUID based api's

2022-11-22 17:41 UTC, nikchern approved these changes

2022-11-22 17:42 UTC, merged