PLT-587:Added Node repave interval support for all infra cluster
spectrocloud/terraform-provider-spectrocloud pull request #322
Opened 2023-07-25 10:32 UTC by SivaanandM

2023-07-26 02:36 UTC, nikchern commented on spectrocloud/resource_cluster_aws.go
> +							Description: "Minimum number of seconds a node should be Ready, before the next node is selected for repave (Applicable only for worker pools)",
we have to document everywhere that default value is 0.

2023-07-26 02:37 UTC, nikchern commented on spectrocloud/resource_cluster_aws.go
> +							Description: "Minimum number of seconds a node should be Ready, before the next node is selected for repave (Applicable only for worker pools)",
```suggestion
							Description: "Minimum number of seconds node should be Ready, before the next node is selected for repave. Default value is `0`",
```

2023-07-26 02:38 UTC, nikchern commented on spectrocloud/resource_cluster_azure.go
> +							Description: "Minimum number of seconds a node should be Ready, before the next node is selected for repave (Applicable only for worker pools)",
```suggestion
							Description: "Minimum number of seconds node should be Ready, before the next node is selected for repave. Default value is `0`",
```

2023-07-26 02:38 UTC, nikchern commented on spectrocloud/resource_cluster_coxedge.go
> +							Description: "Minimum number of seconds a node should be Ready, before the next node is selected for repave (Applicable only for worker pools)",
```suggestion
							Description: "Minimum number of seconds node should be Ready, before the next node is selected for repave. Default value is `0`",
```

2023-07-26 02:38 UTC, nikchern commented on spectrocloud/resource_cluster_edge_native.go
> +							Description: "Minimum number of seconds a node should be Ready, before the next node is selected for repave (Applicable only for worker pools)",
```suggestion
							Description: "Minimum number of seconds node should be Ready, before the next node is selected for repave. Default value is `0`",
```

2023-07-26 02:39 UTC, nikchern commented on spectrocloud/resource_cluster_edge_vsphere.go
> +							Description: "Minimum number of seconds a node should be Ready, before the next node is selected for repave (Applicable only for worker pools)",
```suggestion
							Description: "Minimum number of seconds node should be Ready, before the next node is selected for repave. Default value is `0`",
```

2023-07-26 02:40 UTC, nikchern commented on spectrocloud/resource_cluster_gcp.go
> +							Description: "Minimum number of seconds a node should be Ready, before the next node is selected for repave (Applicable only for worker pools)",
```suggestion
							Description: "Minimum number of seconds node should be Ready, before the next node is selected for repave. Default value is `0`",
```

2023-07-26 02:40 UTC, nikchern commented on spectrocloud/resource_cluster_libvirt.go
> +							Description: "Minimum number of seconds a node should be Ready, before the next node is selected for repave (Applicable only for worker pools)",
```suggestion
							Description: "Minimum number of seconds node should be Ready, before the next node is selected for repave. Default value is `0`",
```

2023-07-26 02:41 UTC, nikchern commented on spectrocloud/resource_cluster_maas.go
> +							Description: "Minimum number of seconds a node should be Ready, before the next node is selected for repave (Applicable only for worker pools)",
```suggestion
							Description: "Minimum number of seconds node should be Ready, before the next node is selected for repave. Default value is `0`",
```

2023-07-26 02:41 UTC, nikchern commented on spectrocloud/resource_cluster_openstack.go
> +							Description: "Minimum number of seconds a node should be Ready, before the next node is selected for repave (Applicable only for worker pools)",
```suggestion
							Description: "Minimum number of seconds node should be Ready, before the next node is selected for repave. Default value is `0`",
```

2023-07-26 02:41 UTC, nikchern commented on spectrocloud/resource_cluster_vsphere.go
> +							Description: "Minimum number of seconds a node should be Ready, before the next node is selected for repave (Applicable only for worker pools)",
```suggestion
							Description: "Minimum number of seconds node should be Ready, before the next node is selected for repave. Default value is `0`",
```

2023-07-26 02:43 UTC, nikchern requested changes
Please address review comments. 
I also suggest to calculate hash on common attributes for machine pool in a separate common function and reuse it.

2023-07-27 08:36 UTC, SivaanandM commented
> Please address review comments. I also suggest to calculate hash on common attributes for machine pool in a separate common function and reuse it.

As discussed it addressed

2023-07-28 06:00 UTC, nikchern requested changes

2023-07-28 06:00 UTC, nikchern commented on spectrocloud/resource_cluster_aws.go
> +			oi["node_repave_interval"] = isControlPlane
should be assigned to node_repave_interval

2023-07-31 04:59 UTC, nikchern requested changes
Just need to fix odd unit test @SivaanandM otherwise looks great now!

2023-08-02 09:58 UTC, SivaanandM commented on spectrocloud/resource_cluster_aws.go
> +		}
resolved

2023-08-02 09:58 UTC, SivaanandM commented on spectrocloud/resource_cluster_aws.go
> +func FlattenControlPlaneAndRepaveInterval(isControlPlane *bool, oi map[string]interface{}) {
resolved

2023-08-10 15:42 UTC, SivaanandM commented
> Just need to fix odd unit test @SivaanandM otherwise looks great now!

unit test completed

2023-08-10 15:43 UTC, SivaanandM commented
> Please address review comments. I also suggest to calculate hash on common attributes for machine pool in a separate common function and reuse it.

done

2023-08-10 15:57 UTC, nikchern approved these changes

2023-08-10 15:57 UTC, merged